zookeeper:
  image: zookeeper:3.4.9
  hostname: zookeeper
  ports:
    - "2181:2181"

mesos-master:
  image: mesosphere/mesos-master:1.7.0
  hostname: mesos-master
  entrypoint: [ "mesos-master" ]
  ports:
    - "5050:5050"
  links:
    - zookeeper
  environment:
    - MESOS_CLUSTER=local
    - MESOS_HOSTNAME=mesos-master.docker
    - MESOS_LOG_DIR=/var/log
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_ROLES=public
    - MESOS_ZK=zk://zookeeper:2181/mesos

mesos-slave1:
  image: mesosphere/mesos-slave:1.7.0
  entrypoint:
    - mesos-slave
  privileged: true
  hostname: mesos-agent1
  ports:
    - "5051:5051"
  links:
    - zookeeper
    - mesos-master
  environment:
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_HOSTNAME=localhost
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_PORT=5051
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
    - MESOS_DOCKER_STOP_TIMEOUT=60secs
    - MESOS_SYSTEMD_ENABLE_SUPPORT=false
    - MESOS_RESOURCES=cpus:4;mem:1280;disk:25600;ports(*):[12000-12999]
  volumes:
    - "/sys:/sys/fs/cgroup"
    - "/var/run/docker.sock:/var/run/docker.sock"

mesos-slave2:
  image: mesosphere/mesos-slave:1.7.0
  entrypoint:
    - mesos-slave
  privileged: true
  hostname: mesos-agent2
  ports:
    - "5052:5052"
  links:
    - zookeeper
    - mesos-master
  environment:
    - MESOS_CONTAINERIZERS=docker,mesos
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_PORT=5052
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD=90secs
    - MESOS_DOCKER_STOP_TIMEOUT=60secs
    - MESOS_SYSTEMD_ENABLE_SUPPORT=false
    - MESOS_RESOURCES=cpus:4;mem:1280;disk:25600;ports(*):[13000-13999]
  volumes:
    - "/sys:/sys/fs/cgroup"
    - "/var/run/docker.sock:/var/run/docker.sock"

marathon:
  image: mesosphere/marathon:v1.6.549
  ports:
    - "8080:8080"
  links:
    - zookeeper
    - mesos-master
  environment:
    - MARATHON_ZK=zk://zookeeper:2181/marathon
    - MARATHON_MASTER=zk://zookeeper:2181/mesos
    - MARATHON_DECLINE_OFFER_DURATION=3600000
    - MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=marathon
    - MARATHON_MESOS_ROLE=public
